/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class chapqalog {
    constructor() {
        this.qalogid = undefined;
        this.cqaid = undefined;
        this.cid = undefined;
        this.qid = undefined;
        this.userAnswer = undefined;
        this.isRight = undefined;
        this.answerTime = undefined;
        this.uid = undefined;
    }

    setQalogid(qalogid) {
        this.qalogid = qalogid;
    }

    getQalogid() {
        return this.qalogid;
    }

    setCqaid(cqaid) {
        this.cqaid = cqaid;
    }

    getCqaid() {
        return this.cqaid;
    }

    setCid(cid) {
        this.cid = cid;
    }

    getCid() {
        return this.cid;
    }

    setQid(qid) {
        this.qid = qid;
    }

    getQid() {
        return this.qid;
    }

    setUserAnswer(userAnswer) {
        this.userAnswer = userAnswer;
    }

    getUserAnswer() {
        return this.userAnswer;
    }

    setIsRight(isRight) {
        this.isRight = isRight;
    }

    getIsRight() {
        return this.isRight;
    }

    setAnswerTime(answerTime) {
        this.answerTime = answerTime;
    }

    getAnswerTime() {
        return this.answerTime;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }
}

chapqalog.className = 'chapqalog';

export {chapqalog}