/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class chapqa {
    constructor() {
        this.cqaid = undefined;
        this.cid = undefined;
        this.qid = undefined;
        this.qtype = "判断/单选/多选";
        this.title = "题目标题";
        this.answer = "[\"A.答案A\",\"B.答案B\"]";
        this.letter = "[\"A\",\"B\"]";
        this.rightAnswer = "[\"A\",\"B\"]";
        this.solution = "正确答案:B";
        this.order = undefined;
    }

    setCqaid(cqaid) {
        this.cqaid = cqaid;
    }

    getCqaid() {
        return this.cqaid;
    }

    setCid(cid) {
        this.cid = cid;
    }

    getCid() {
        return this.cid;
    }

    setQid(qid) {
        this.qid = qid;
    }

    getQid() {
        return this.qid;
    }

    setQtype(qtype) {
        this.qtype = qtype;
    }

    getQtype() {
        return this.qtype;
    }

    setTitle(title) {
        this.title = title;
    }

    getTitle() {
        return this.title;
    }

    setAnswer(answer) {
        this.answer = answer;
    }

    getAnswer() {
        return this.answer;
    }

    setLetter(letter) {
        this.answer = letter;
    }

    getLetter() {
        return this.letter;
    }

    setRightAnswer(rightAnswer) {
        this.rightAnswer = rightAnswer;
    }

    getRightAnswer() {
        return this.rightAnswer;
    }

    setSolution(solution) {
        this.solution = solution;
    }

    getSolution() {
        return this.solution;
    }

    setOrder(order) {
        this.order = order;
    }

    getOrder() {
        return this.order;
    }
}

chapqa.className = 'chapqa';

export {chapqa}