/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class chaplog {
    constructor() {
        this.logid = undefined;
        this.cid = undefined;
        this.qid = undefined;
        this.uid = undefined;
        this.currentIndex = undefined;
        this.isDone = undefined;
        this.score = undefined;
        this.startDate = undefined;
        this.endDate = undefined;
        this.remark = undefined;
    }

    setLogid(logid) {
        this.logid = logid;
    }

    getLogid() {
        return this.logid;
    }

    setCid(cid) {
        this.cid = cid;
    }

    getCid() {
        return this.cid;
    }

    setQid(qid) {
        this.qid = qid;
    }

    getQid() {
        return this.qid;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }

    setCurrentIndex(currentIndex) {
        this.currentIndex = currentIndex;
    }

    getCurrentIndex() {
        return this.currentIndex;
    }

    setIsDone(isDone) {
        this.isDone = isDone;
    }

    getIsDone() {
        return this.isDone;
    }

    setScore(score) {
        this.score = score;
    }

    getScore() {
        return this.score;
    }

    setStartDate(startDate) {
        this.startDate = startDate;
    }

    getStartDate() {
        return this.startDate;
    }

    setEndDate(endDate) {
        this.endDate = endDate;
    }

    getEndDate() {
        return this.endDate;
    }

    setRemark(remark) {
        this.remark = remark;
    }

    getRemark() {
        return this.remark;
    }
}

chaplog.className = 'chaplog';

export {chaplog}