/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class chaplist {
    constructor() {
        this.cid = undefined;
        this.qid = 1;
        this.title = undefined;
        this.level = undefined;
        this.remark = undefined;
        this.order = undefined;
    }

    setCid(cid) {
        this.cid = cid;
    }

    getCid() {
        return this.cid;
    }

    setQid(qid) {
        this.qid = qid;
    }

    getQid() {
        return this.qid;
    }

    setTitle(title) {
        this.title = title;
    }

    getTitle() {
        return this.title;
    }

    setLevel(level) {
        this.level = level;
    }

    getLevel() {
        return this.level;
    }

    setRemark(remark) {
        this.remark = remark;
    }

    getRemark() {
        return this.remark;
    }

    setOrder(order) {
        this.order = order;
    }

    getOrder() {
        return this.order;
    }
}

chaplist.className = 'chaplist';

export {chaplist}