/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class userHeadImg {
    constructor() {
        this.uid = undefined;
        this.imgurl = undefined;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }

    setImgurl(imgurl) {
        this.imgurl = imgurl;
    }

    getImgurl() {
        return this.imgurl;
    }
}

userHeadImg.className = 'userHeadImg';

export {userHeadImg}